# Hyprland configuration overrides
# Add your custom settings here

# Example overrides:
# $mainMod = SUPER
# $terminal = uwsm app -- ghostty
# $browser = chromium --force-device-scale-factor=0.8

# Use single default monitor (see all monitors with: hyprctl monitors)
monitor=,preferred,auto,1

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    border_size = 1

    # El orden es: Color1 Color2 Ángulo
    # rgba(RRGGBBAA) o rgb(RRGGBB)
    # col.active_border = rgba(a1a1a1ee) rgba(606060ee) rgba(0c0c0cee) 45deg
    col.active_border = rgba(89b4faee) rgba(0c0c0cee) rgba(F5C2E7ee) 25deg

    # Use master layout instead of dwindle
    # layout = master
}

group {

    # El orden es: Color1 Color2 Ángulo
    # rgba(RRGGBBAA) o rgb(RRGGBB)
    # col.active_border = rgba(a1a1a1ee) rgba(606060ee) rgba(0c0c0cee) 45deg
    col.border_active = rgba(89b4faee) rgba(0c0c0cee) rgba(F5C2E7ee) 25deg

}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 16
}

# trigger when the switch is turning on
# bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
# bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.6"

# Application unbindings
unbind = SUPER SHIFT, RETURN
unbind = SUPER SHIFT, F
unbind = SUPER ALT SHIFT, F
unbind = SUPER SHIFT, B
unbind = SUPER SHIFT ALT, B
unbind = SUPER SHIFT, M
unbind = SUPER SHIFT, N
unbind = SUPER SHIFT, D
unbind = SUPER SHIFT, G
unbind = SUPER SHIFT, O
unbind = SUPER SHIFT, W
unbind = SUPER SHIFT, SLASH

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
unbind = SUPER SHIFT, A
unbind = SUPER SHIFT ALT, A
unbind = SUPER SHIFT, C
unbind = SUPER SHIFT, E
unbind = SUPER SHIFT, Y
unbind = SUPER SHIFT ALT, G
unbind = SUPER SHIFT CTRL, G
unbind = SUPER SHIFT, P
unbind = SUPER SHIFT, X
unbind = SUPER SHIFT ALT, X
unbind = ALT, TAB

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bindd = , F12, Toggle scratchpad, togglespecialworkspace, scratchpad
bindd = SUPER, F12, Move window to scratchpad, movetoworkspacesilent, special:scratchpad
bindd = ALT, TAB, Former workspace, workspace, previous
